### ISSUE TITLE
Ability to download mods for an older version of Minecraft.

### ISSUE THREAD

**Issue by HAMM3REXTREME** [jakobkmar/pacmc#16]
You can only `search` for mods for a specific version of Minecraft with the `-g` option.

The `-g` option should also work when installing mods.

**Comment by jakobkmar** [comment]
The minecraft version is determined by the version of the archive. You can view the archive version using `pacmc archive list`.

To change the minecraft version of an archive use `pacmc archive version [mcversion] ([optional archivename])`.

You can also create secondary multiple archives as "profiles" and use `pacmc load` to load them into the .minecraft archive.

**Comment by jakobkmar** [comment]
I will close this for now, if you feel that the above solutions don't work for you, feel free to reopen.
