### ISSUE TITLE
Show mod version

### ISSUE THREAD

**Issue by JustCryen** [jakobkmar/pacmc#17]
Would it be possible to see what version of the mod is available in the "repos" before installing it?
Ideally it would show with the `search` command when listing packages.
It would be also nice when listing already downloaded mods with `list`.

Additionally when using `search`. an indication if the mod is already installed would be realy nice too.

I'm gonna attach a screenshot as an example of how does it work with pacman.
![Screenshot from 2021-12-12 15-57-52](https://user-images.githubusercontent.com/41633661/145717524-c7ddf648-5953-4d41-9e30-4d92cf300ce9.png)

**Comment by jakobkmar** [comment]
This is planned, thanks for creating a tracking issue!

**Comment by jakobkmar** [comment]
This feature is now implemented and will be available with the next release!
