### ISSUE TITLE
[Feature Request] Allow multiple install arguments

### ISSUE THREAD

**Issue by CozzyBro2** [jakobkmar/pacmc#18]
![image](https://user-images.githubusercontent.com/76234965/145859327-7ddf3dc6-e808-4fac-9378-51560ad4df9a.png)

As shown in the image, attempting to install multiple mods at once will throw an 'Extra Argument' error. 

Currently, as somebody who does a lot of bulk installation as I migrate my server around different versions, I think this feature would be very handy as a time saver. 

Sort of like how you can do this with pacman:
```
pacman -S base base-devel linux-zen vim vi xorg 
```
It doesn't seem like there's anything stopping this from being a feature, as extra forms of the install command are achieved using flags, instead of multiple arguments.

**Comment by jakobkmar** [comment]
Yes there is nothing speaking against this feature.

**Comment by jakobkmar** [comment]
This is now implemented in the rewrite and will be available with the next release.
