### ISSUE TITLE
mod name in file name

### ISSUE THREAD

**Issue by fischer-felix** [jakobkmar/pacmc#19]
Hi, I think it would be nice, if the filename of the .jar would contain the actual mod's name instead of a string of characters (for example `pacmc_modrinth_indium.jar` instead of `pacmc_modrinth_Orvt0mRa_1ApUEVoW_0.jar`.

**Comment by jakobkmar** [comment]
Hey, I totally get that these names aren't optimal if you manually look into your mods folder, but there is a good reason for them:

Without storing the mod and version id in the filename itself, pacmc would have to maintain a separate file or database, where it stores which file is what. This could lead to major inconsistencies, causing pacmc to lose control over the files and not even `pacmc refresh` being able to fix this without manual intervention.

I hope you understand this and those filenames aren't too bad. :)

(Also, please note that these files shouldn't be touched manually anyway, as they are managed by the package manager. And for listing your mods there is always `pacmc list`.)

**Comment by fischer-felix** [comment]
Would it not be possible to just append/prepend the name of the mod to the filename?

**Comment by jakobkmar** [comment]
That would be possible, but this way filenames would get really long, and if I remember correctly windows has a pretty low file name length limit.

**Comment by fischer-felix** [comment]
Doubt that's going to be the problem
![Screenshot_2021 12 16_22:12:18](https://user-images.githubusercontent.com/65448408/146449683-73fa9dd4-9f0d-4cc8-b837-6a826dc173cf.png)

**Comment by fischer-felix** [comment]
How is naming/getting a file by name currently handled? Do you identify pacmc files by the `pacmc` at the start?

**Comment by jakobkmar** [comment]
> Doubt that's going to be the problem ![Screenshot_2021 12 16_22:12:18](https://user-images.githubusercontent.com/65448408/146449683-73fa9dd4-9f0d-4cc8-b837-6a826dc173cf.png)

yeah it can be enabled, but it is not enabled by default

**Comment by jakobkmar** [comment]
> How is naming/getting a file by name currently handled? Do you identify pacmc files by the `pacmc` at the start?

correct, the `pacmc_` at the beginning (and whether the rest of the file name is correct) identifies a pacmc mod file

**Comment by JustCryen** [comment]
Filenames right now are roughly 35 chars long, if we remove "pacmc" and replace hosting with 2 letter equivalent (CF / MR) these names are reduced to something like 23.
You could still identify files but this time by directly checking the hosting. 

Also, what precisely is the file name limit on Windows?
I wasn't aware of one and making the mods folder less managable is not a good idea.
Even though we use pacmc to manage mods, sometimes it's required to manually intervene and having a name of the mod would be nice.

**Comment by jakobkmar** [comment]
I also think something needs to be changed about the file names, I am just not quite sure yet in which way, the one with the repository as the prefix definitely is a valid option.

**Comment by jakobkmar** [comment]
I kind of decided to use the following scheme (examples):
Modrinth Sodium: `mr_sodium_AANobbMI.jar`
CurseForge : `cf_fabric_api_306612.jar`

So its repo, slug, modid

**Comment by SquareManRan** [comment]
For no reasons other than organization and cohesion, I personally feel that `repo, modid, slug` would work better. The beginning of the slug would happen at roughly the same character for every mod, which would increase readability greatly, e.g. when scanning down your modlist.

**Comment by jakobkmar** [comment]
mh not sure, I prefer the first approach, because users want to see the slug, and placing it at the front of the file name helps making it clearer if you don't care about the modid

>  The beginning of the slug would happen at roughly the same character for every mod

that would also be the case with the other approach, as the repo will always be a 2 character string

**Comment by SquareManRan** [comment]
You see you make some excellent points. I was fairly tired when I made that comment my apologies 😅

**Comment by jakobkmar** [comment]
In the future, mod files will have [this structure](https://github.com/jakobkmar/pacmc/blob/be79b605d4d45b869491227ac36a6a6742ca3f12/pacmc-app/src/commonMain/kotlin/net/axay/pacmc/app/data/ModFile.kt#L8).
