### ISSUE TITLE
[Feature Request] Add option to disable dependency management

### ISSUE THREAD

**Issue by Cloudperry** [jakobkmar/pacmc#20]
Sometimes the dependencies of mods are just wrong. For example the mod [Syncmatica](https://www.curseforge.com/minecraft/mc-mods/syncmatica) has Malilib and Litematica as dependencies, but both of those are not required on a server just like the [setup instructions](https://github.com/End-Tech/syncmatica) say. I'm sure there are many more cases of mods dependencies being wrong with mods that are for both the client and the server. 

The optimal solution for this would be adding an option to disable dependency management per mod. Just having an option to disable dependency management completely would be a really good solution as well. I think that managing mods' dependencies manually is really easy, because most mods have 0-2 dependencies.

Edit: Removed paragraph about my dumb old way to manage server and client mods.

**Comment by Cloudperry** [comment]
Soon after posting this I thought of having the same mods folder for client and server and it seems that Fabric handles that really well. All the mods that are client only just don't get loaded on the server and vice versa. With that approach duplicate dependencies in client/server mods are not an issue anymore.

**Comment by JustCryen** [comment]
To be fair, you probably could symling the directory and manage everything from one archive

**Comment by Cloudperry** [comment]
Yeah thats exactly what I meant with my last comment. I meant that I will have one mods folder (archive) and symlink the server and client folders there. The reason I managed my mods separately before was that I didn't know Fabric would handle same mods folder for client/server that well.
