### ISSUE TITLE
False positive in dependency removal.

### ISSUE THREAD

**Issue by JustCryen** [jakobkmar/pacmc#22]
If a mod depending on FabricAPI is outdated, it gets removed before a new version will be downloaded.
That's ok but this causes pacmc to flag Fabric API as unneeded.
`Removing the dependency Fabric API because it is no longer needed`

Suggestion: move the dependency check to appear after `Updating mods` one and eventually run `Deleting old files` again to flush actually unneeded dependencies.

**Comment by jakobkmar** [comment]
Hey, I already noticed this issue, thanks for reporting it.

I am currently rewriting the whole install process, including version and dependency resolving, this will fix this, pretty sure! I hope you can wait until then 👀

**Comment by JustCryen** [comment]
Sure ;P
It just requires running a manual install after an update so it's not a big issue tbh.
Just a little bit annoying.

I'm reporting the things I find to: 1 help make this project better, 2 help keep track of some undocumented issues.
This program already is pretty good and really useful, thanks for the effort!

**Comment by jakobkmar** [comment]
Yes sure report everything that should be improved, it helps to not forget these issues - and also to keep them in mind when doing the rewrite.

**Comment by jakobkmar** [comment]
Should be fixed in the upcoming 0.5.0 release (rewrite).
