### ISSUE TITLE
Typo in README for paru install instructions.

### ISSUE THREAD

**Issue by sharifhsn** [jakobkmar/pacmc#27]
The instructions in the README to install pacmc using paru are incorrect and will not work. `paru install pacmc` will search the Arch and AUR repositories for a package with the keywords "install" and "pacmc", of which there are none. The correct command would be either `paru pacmc`, which would interactively search and install pacmc with similar behavior to pacmc itself, or `paru -S pacmc` which would install pacmc directly similar to how pacmc will install mods using a mod ID.

**Comment by jakobkmar** [comment]
You are right, I messed it up when migrating the old instructions to the new table, thanks for reporting this.
