### ISSUE TITLE
Update command doesn't update to newest version

### ISSUE THREAD

**Issue by endrjux** [jakobkmar/pacmc#31]
It seems "update" command can't always find the newest version of the mod (at least for curseforge mods), for example:

I have version 3.4.1 of `curseforge/357540` installed (1.18.1).
But the latest version is 3.4.2:
![image](https://user-images.githubusercontent.com/688476/158883084-59d34ce0-10c0-4eda-b63e-f95d83f58a1e.png)

I suspect it might be because this version is marked as "beta". Unfortunately there is no way to select which release type should be installed.

**Comment by jakobkmar** [comment]
Hey, seems like you are right, when having the archive version set to 1.18.1 it does not install the latest beta version even though it is marked to be compatible.

I will rewrite the Curseforge handling for the new documented Curseforge API anyways, so I will have a look at this then.
Additionally, it is worth noting that in the future pacmc will support to manually select a version.

If you really need that new 3.4.2 version of InventoryHUD, the only short term solution is to use a 1.18.2 archive.

Thank you for reporting the issue :)

**Comment by endrjux** [comment]
Thanks for superfast response! It's probably reasonable to update mc to newest version anyway (not sure if other mods I use were updated to 1.18.2 though, but that's a different story).

Pacmc is really great, can't wait for that new version. I appreciate your work!

**Comment by jakobkmar** [comment]
I am closing this now, if it happens again in the rewrite and with the new Curseforge API which pacmc now uses, feel free to reopen.
