### ISSUE TITLE
Add unstable minecraft versions

### ISSUE THREAD

**Issue by btwonion** [jakobkmar/pacmc#47]
Add unstable versions like 1.19-rc2 to pacmc.

**Comment by jakobkmar** [comment]
This is 100% a thing which should be supported.
While RCs and pre releases are easy, some challenges for the implementation are:
- reliably ordering snapshots like `22w16a`
- dealing with special names like `22w13oneblockatatime`
in the future, when pacmc is a launcher:
- dealing with old names like `c0.30_01c` or `rd-160052`
- correctly ordering old betas like `b1.6.6`
