### ISSUE TITLE
Modrinth support

### ISSUE THREAD

**Issue by jakobkmar** [jakobkmar/pacmc#7]
- maybe make it an optional repository (just for the search command, not for the direct installation, in that case it should be enabled by default)
- always use it as a fallback if curseforge can't be reached

This requires an intermediate representation of file and project responses - because the two APIs are different.

**Comment by bluefireoly** [comment]
- Modrinth is now the primary source for mods used by pacmc

I still have to come up with a solution how duplicated dependencies (e.g. Modrinth Fabric API vs Curseforge Fabric API) should be handled.
